### ISSUE TITLE
Packaging improvements

### ISSUE THREAD

**Issue by jayvdb** [OpticGenius/pypi-download-tarball#5]
I have created a rpm package for openSUSE, but not submitted it yet.

https://build.opensuse.org/package/view_file/home:jayvdb:py-new/python-download-tarball/python-download-tarball.spec?expand=1

Two minor ways this can be improved is
- test_tar_extract and test_zip_extract needed to be disabled, because they fetch from the internet.  rpm's are built in isolated VMs, without internet access.  Tests need to run offline.  There is already a test for fetching from the internet, which I disabled, so these other two tests should use a test case which doesnt need the internet.
- bin name `download` is way too generic.  Even `download-tarball` isnt intuitive (as a system wide bin name in /usr/bin) as it only downloads from one source.  `pypi-download` is already taken by package `stdeb`.  What about renaming the bin script to `pypi-download-tarball`?

**Comment by OpticGenius** [comment]
@jayvdb Thanks for the feedback. I've updated this package to use the `pypi-download-tarball` binary instead. I also agree on disabling the unit tests, which I have done as well. I don't like them and are not needed. Not sure what I was thinking at the time haha :P

I'll probably create a V2 of this project in the future

**Comment by OpticGenius** [comment]
Deprecated this repo. No longer going to support it because it has too many problems.
