### ISSUE TITLE
Requirements file parser doesnt ignore comments

### ISSUE THREAD

**Issue by jayvdb** [OpticGenius/pypi-download-tarball#6]
Lines beginning with `#` should be ignored.

There are a few requirements parsers available.  https://github.com/di/pip-api is the one I usually use as it is a wrapper for the one in pip, however other simpler ones also exist and might be more appropriate at this stage of development.

**Comment by jayvdb** [comment]
https://github.com/sarugaku/requirementslib is another, used by pipenv.

**Comment by OpticGenius** [comment]
Good feedback. I'll keep that in mind when I make a newer version of this package. I've deprecated it for now because it needs to be redone.
